---
# sourcehut build manifest

image: debian/stable
arch: amd64

tasks:
    - checkout: |
        git clone https://github.com/$GITHUB_REPO
    - build-dep: |
        cd python-simpleproject
        sudo make build-dep
    - test: |
        cd python-simpleproject
        make test
