---
# CI config for https://gitlab.com/
# - free accounts available, TODO: document the usage limits

test:
    image: debian:stable
    script:
        - apt-get install -y make
        - make build-dep
        - make test
