---
# CI config for https://circleci.com
# - free accounts, ~2500 minutes per week included
#   (free accounts are limited to 1 concurrent job)

version: 2.1

jobs:
    test:
        machine:
            image: ubuntu-2004:202010-01
        steps:
            - checkout
            - run: sudo apt-get update
            - run: sudo make build-dep
            - run: PATH=/usr/bin:/bin:/usr/sbin:/sbin make test

workflows:
    main:
        jobs:
            - test
