version: 2.1

environment:
    PATH: /usr/bin:/bin:/usr/sbin:/sbin

jobs:
    test:
        machine:
            image: ubuntu-2004:202010-01
        steps:
            - checkout
            - run: sudo apt-get update
            - run: sudo make build-dep
            - run: make test

workflows:
    main:
        jobs:
            - test
